FROM ubuntu:jammy as base

RUN apt update && apt -y upgrade
RUN apt install -y z3 cvc4
RUN apt install -y wget

RUN mkdir -p /nix/store/gckxrwrq6rfnib7j62m3mmn09d3qskqg-z3-4.8.10/bin
RUN ln -s /usr/bin/z3 /nix/store/gckxrwrq6rfnib7j62m3mmn09d3qskqg-z3-4.8.10/bin/z3
RUN wget https://github.com/dapphub/dapptools/releases/download/seth%2F0.11.0/hevm -P /bin
RUN chmod a+x /usr/bin/hevm
